### PR TITLE
remove print._coxnet()

### PR DESCRIPTION
**Pull request by EmilHvitfeldt**
I'm not able easily find the origin of this function. but as it stands it appears to have been a near copy of the old `print.model_fit()`.

The other errors appears to be related to https://github.com/tidymodels/parsnip/issues/1109

### CODE REVIEW

**Comment by simonpcouch** [comment]
It does seem like some `"The training data has been saved for prediction."` lines are being removed in snaps. Unless this is blocking you on a parsnip PR, I'll defer to @hfrick on reviewing this one, as she's more likely to understand how important it is that we call that out.

**Comment by hfrick** [comment]
That line is the reason for this print method to exist :) Could you update it rather than remove it?

**Comment by EmilHvitfeldt** [comment]
I used `NextMethod()` to make it so `print.model_fit()` is in charge of the actually printing, and `print._coxnet()` only adds extra.

**Comment by hfrick** [comment]
Excellent, thank you! 🙌 I've taken that idea just a smidge further, leaning into the parnsip method for everything but that one extra sentence.

**Pull request merged**
