### PR TITLE
Move model spec for `survival_reg` to parsnip

### PR DESCRIPTION
**Pull request by hfrick**
This is a joint PR with https://github.com/tidymodels/parsnip/pull/449 on {parsnip} to move the model specification for `survival_reg` to parsnip (but keep the engines in {censored}), see also https://github.com/EmilHvitfeldt/censored/issues/2#issuecomment-788429365

I've also added the documentation of the engine details from the original `parsnip::surv_reg()`.

The PR on parsnip should be merged first.

### CODE REVIEW

**Comment by hfrick** [comment]
I think the failures in the tests for the Cox model may be due to recent changes in {survival}. From the corresponding [NEWS](https://cran.r-project.org/web/packages/survival/news.html) file:

> * Error in survit.coxph for a multistate fit with strata, an array dimension was wrong (but contents correct). It led to downstream problems with print and plot. Pointed out by Matthew Hall. 
> * Add ability for a multistate coxph model to have shared (proportional) baselines for transitions.
> * The coxph routine no longer recenters 0/1 predictors (fit$mean will be 0), per the default value of the new nocenter argument. Application of survfit to a coxph model without specifying newdata remains a bad idea, but this change makes it a little less bad since for factors the curve will refer to the reference level. The results of predict(fit) are now more defensible for a factor variable.
> * Add an explicit error message for survreg() with a frailty term. This usage was never supported – it is integrating out the appropriate density for a coxph model, which is the wrong one for survreg – but because the code would run we've found that people assumed it must be right, despite a statement to the contrary in the survival vignette. Long overdue fix.

**Comment by hfrick** [comment]
The failing test for the survival predictions is due to [this change](https://github.com/therneau/survival/commit/98fefd045277a9fb726b0b03b3b8bb28fa252bd9#diff-7d27291cce45963171b08e8e13e3318cb424d181b2cc8ee19a1331d86c2761b8L126) in version 3.2-8 of the survival package.

**Review by EmilHvitfeldt — APPROVED** [review]
LGTM!

**Comment by hfrick** [comment]
fixed failing test in #37, tests are passing now

**Pull request merged**
