### PR TITLE
aorsf version 0.1.2

### PR DESCRIPTION
**Pull request by bcjaeger**
This PR has two aims: 

1. Small changes to `test-rand_forest_aorsf.R` and `DESCRIPTION` to prepare for release of version 0.1.2 of `aorsf` (#287).
2. Makes `survival_prob_orsf` use a `parsnip` object instead of an `aorsf` object (#283).  

I am posting this before the `censored` team returns to the office so that I can try to make amendments if tests fail. I do not expect any review before the team returns.

### CODE REVIEW

**Comment by hfrick** [comment]
Thanks so much for the PR @bcjaeger ! 🙌 

The updates to the tests are great! Do you happen to know why the checks fails on Windows with R 4.1? It's asking for a newer version of the C++ compiler and I'm trying to understand why it fails for this one action only.

I appreciate you wanting to take care of all aorsf-related issues! Generally it's best to send separate PRs for separate issues. In this case, the changes for #283 are breaking changes. I'll need a moment to decide if we want to go down that route or be more gentle via, e.g., a deprecation, since this is an exported function (even though it's marked with keyword internal). I can focus on this again towards the end of the week but if you'd like to move forward with the updated tests before then, could you please remove the changes for #283 from this PR?

**Comment by hfrick** [comment]
Are we hitting this with the failed action? https://github.com/ropensci/aorsf/blob/main/src/AAA_check_cpp_version.cpp

There is also https://github.com/ropensci/aorsf/commit/022821f327ea3d9e77b33188983f328124e4a1a5 so do we still need a C++ 14 compiler or not?

**Comment by bcjaeger** [comment]
> Thanks so much for the PR @bcjaeger ! 🙌

My pleasure. `censored` is a great package and its organization makes it easy for a newcomer like me to do things. 

> I can focus on this again towards the end of the week but if you'd like to move forward with the updated tests before then, could you please remove the changes for https://github.com/tidymodels/censored/issues/283 from this PR?

Definitely. That makes a lot of sense. I was too hasty trying to do two things at once. I will revert the changes for #283.

> Are we hitting this with the failed action? https://github.com/ropensci/aorsf/blob/main/src/AAA_check_cpp_version.cpp

Correct! With R 4.1, the default C++ compiler is 11, and I believe from R 4.3 the default compiler became 14, which is why we only see this issue in the Windows 4.1 action.

> There is also https://github.com/ropensci/aorsf/commit/022821f327ea3d9e77b33188983f328124e4a1a5 so do we still need a C++ 14 compiler or not?

Short answer: Yes, we need the C++14 compiler.

Long answer: I apologize for the confusing commit history. CRAN has some specific policies about C++ requirements that I only learned about recently. CRAN checks will throw a note if `makevars` includes something like `CXX_STD = CXX14` or `SystemRequirements: C++14` in `DESCRIPTION`, and that is why I include the `AAA_check_cpp_version.cpp` file instead of using the more convenient options. 

The issue with running tests on 4.1 could be resolved if I add `CXX_STD = CXX14`  to the `makevars.win` file, but then I think CRAN would have an issue. I'm not sure what would be best.

**Comment by bcjaeger** [comment]
> The issue with running tests on 4.1 could be resolved if I add CXX_STD = CXX14 to the makevars.win file, but then I think CRAN would have an issue. I'm not sure what would be best.

Can confirm that adding this to `aorsf/src/makevars.win` fixed the issue, but the action will break again if I need to take this out of `makevars` to get `aorsf` 0.1.2 on CRAN. Maybe they will allow it if I link this PR.

**Comment by hfrick** [comment]
Given that the new version doesn't break any of censored's functionality wrt aorsf but rather only breaks the tests, I don't want to force people to upgrade their version of aorsf. I've modified the tests to work with old and new versions of aorsf and removed the version requirement in the DESCRIPTION.

**Comment by bcjaeger** [comment]
Thank you!

**Pull request merged**
